### ISSUE TITLE
#Input add mask parameter to distinguish categorial and numeric features

### ISSUE THREAD

**Issue by ismagin** [scaled-ml/Scaled-ML#22]
ftrl --mask *CNNNNNNCCCCCCC

proposed:
*CCCCC = first item is label, next 5 are categories(6 total)
*CCNNNC = first item is label, next 2 are categories, next 3 are numerics, last 1 is category(7 total)
NNNN  = 4 numeric features(no label supplied)

**Comment by Onuchin-Artem** [comment]
I think there is a better idea.

ftrl --numerical-columns 1,3,8-9,32-
You specify numerical columns just like in cut -f.
 because if you have about 50 columns the mask can be pretty long and error prone.
